export type PowerState        = 'on' | 'off';
export type AvailabilityState = 'available' | 'unavailable';
export type LockState         = 'locked' | 'unlocked';

/**
 * A branded string type that identifies an HA entity and carries its TypeScript type
 * as a phantom type parameter. Values are produced by the type generator.
 */
export type EntityId<T extends HaEntity = HaEntity> =
  string & { readonly _brand: 'EntityId'; readonly _type: T };

export type HaDomain = string;
export const haEvents = ['added', 'removed', 'updated', 'state-changed'] as const;
export type HaEvent = (typeof haEvents)[number];

export type HaAttributes = Record<string, unknown>;
export type HaGroups     = Record<string, HaEntity>;

export type HaEntity = {
  entity_id:    string;
  id:           string;
  name:         string;
  domain:       string;
  state:        string;
  groups:       HaGroups;
  attributes:   HaAttributes;
  last_updated: Date;
  last_changed: Date;
};

// AnyHaEntity is an alias kept for internal use; specific subtypes are generated by the type generator.
export type AnyHaEntity = HaEntity;
